version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14-alpine
    ports:
      - 8001:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=artmy278
      - POSTGRES_DB=db